[package]
edition.workspace = true
name = "macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
anchor-lang-idl = { workspace = true }
anyhow = "1.0.86"
bs58 = "0.5.1"
heck = "0.5.0"

proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "1", features = ["full", "parsing"] }
