[package]
edition.workspace = true
name = "classifier-core"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "classifier_core"

[dependencies]
anchor-lang = { workspace = true }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }

actions = { version = "0.1.0", path = "../actions" }
anyhow = "1.0.86"
bincode = "1.3.3"
bs58 = "0.5.1"
indextree = "4.7.2"
macros = { version = "0.1.0", path = "../macros" }
thiserror = "1.0.63"
tracing = "0.1.40"
