[package]
edition.workspace = true
name = "classification"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "classification"

[dependencies]
solana-program = { workspace = true }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }

bincode = "1.3.3"
thiserror = "1.0.63"
tracing = "0.1.40"
base58 = "0.2.0"
indextree = "4.7.2"
anyhow = "1.0.86"
