[package]
edition.workspace = true
name = "actions"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "actions"

[dependencies]
anchor-lang = { workspace = true }
solana-sdk = { workspace = true }

borsh = "^0.10.3"
macros = { version = "0.1.0", path = "../macros" }
serde.workspace = true
classifier-core = { version = "0.1.0", path = "../classifier-core" }
anyhow = "1.0.86"
