[package]
edition.workspace = true
name = "inspection"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "inspection"

[dependencies]
actions = { version = "0.1.0", path = "../actions" }
base58 = "0.2.0"
classifier-core = { version = "0.1.0", path = "../classifier-core" }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
spl-token = { workspace = true }

indextree = "3.0"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.63"
action-tree = { version = "0.1.0", path = "../action-tree" }
tracing = "0.1.40"
