[package]
edition.workspace = true
name = "inspection"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "inspection"

[dependencies]
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
spl-token = { workspace = true }

actions = { version = "0.1.0", path = "../actions" }
base58 = "0.2.0"
classifier-core = { version = "0.1.0", path = "../classifier-core" }
mongodb = "3.1.0"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.63"
tracing = "0.1.40"
