[package]
edition.workspace = true
name = "inspection"
version = "0.1.0"

[lib]
crate-type = ["lib"]
name = "inspection"

[dependencies]
base58 = "0.2.0"
classification = { version = "0.1.0", path = "../classification" }
solana-sdk = { workspace = true }
solana-transaction-status = { workspace = true }
spl-token = { workspace = true }

thiserror = "1.0.63"

indextree = "3.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11"
