[package]
edition = "2021"
name = "cli"
version = "0.1.0"

[dependencies]
solana-client = { workspace = true }
solana-transaction-status = { workspace = true }

clap = { version = "4.5.16", features = ["derive"] }
inspection = { version = "0.1.0", path = "../inspection" }
