[package]
edition = "2021"
name = "cli"
version = "0.1.0"

[dependencies]
solana-client = { workspace = true }
solana-transaction-status = { workspace = true }

clap = { version = "4.5.16", features = ["derive", "env"] }
classifier-core = { version = "0.1.0", path = "../classifier-core" }
inspection = { version = "0.1.0", path = "../inspection" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
actions = { version = "0.1.0", path = "../actions" }
classifier-handler = { version = "0.1.0", path = "../../classifiers/classifier-handler" }
action-tree = { version = "0.1.0", path = "../action-tree" }
tokio = "1.40.0"
time-machine-api = { version = "0.1.0", path = "../api" }
